### ISSUE TITLE
projects/invoice return 404 

### ISSUE THREAD

**Issue by sicksand** [shivampaw/UltimateCRM#16]
Hi,

I'm just do a fresh install and on admin page, the projects and invoices link return 404. here are the logs.

```[2017-09-20 02:51:12] production.ERROR: ErrorException: Trying to get property of non-object in /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Controllers/ClientsOnlyController.php:81
Stack trace:
#0 /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Controllers/ClientsOnlyController.php(81): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/shafiqmu...', 81, Array)
#1 [internal function]: App\Http\Controllers\ClientsOnlyController->allProjects()
#2 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('allProjects', Array)
#4 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ClientsOnlyController), 'allProjects')
#5 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#7 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Middleware/IsClient.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\IsClient->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /Users/shafiqmustapa/Sites/UltimateCRM/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 {main}```

**Comment by shivampaw** [comment]
Hi

What setup instructions did you follow and can you give me the full URL for the pages you’re trying to visit.

Thanks

**Comment by sicksand** [comment]
I'm following the Installation instruction on the main page. And my url is http://localhost/UltimateCRM/public/invoices

**Comment by shivampaw** [comment]
Ok so with Laravel you want the document root to be the public directory. That’s probably what’s causing the problem. 

Have you considered using valet? It’s super easy to setup and works great with Laravel apps.

**Comment by sicksand** [comment]
what if i'm using .htaccess to get rid the public?

**Comment by shivampaw** [comment]
Then you should just need to set your document root to the public directory.

**Comment by shivampaw** [comment]
You should also use a separate virtual host for each app instead of using it as a sub directory of localhost.

**Comment by sicksand** [comment]
I am using ```php artisan serve``` but still there is error.

**Comment by shivampaw** [comment]
I will try and replicate this when I’m home and get back to you within 12 hours.

**Comment by shivampaw** [comment]
So when you use `artisan serve` do you visit http//:localhost:8000 and see the normal login screen? What happens when you login etc. Where do the errors come up and what's the URL?

**Comment by sicksand** [comment]
The login appears, and I'm able to login using artisan create SuperAdmin. The dashboard is appeared. Also I'm able to get the register screen to appear by adding RegistrationController

**Comment by shivampaw** [comment]
So what’s the URL for the error and the error stacktrace?

**Comment by sicksand** [comment]
Here is the url and the stack error

![screen shot 2017-09-21 at 4 00 03 pm](https://user-images.githubusercontent.com/305408/30685034-0b8cbbac-9ee6-11e7-896d-4682a7c4523a.png)

```
2017-09-21 07:59:43] production.ERROR: ErrorException: Trying to get property of non-object in /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Controllers/ClientsOnlyController.php:26
Stack trace:
[2017-09-21 07:59:43] production.ERROR: ErrorException: Trying to get property of non-object in /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Controllers/ClientsOnlyController.php:26
Stack trace:
#0 /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Controllers/ClientsOnlyController.php(26): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/shafiqmu...', 26, Array)
#1 [internal function]: App\Http\Controllers\ClientsOnlyController->allInvoices()
#2 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('allInvoices', Array)
#4 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ClientsOnlyController), 'allInvoices')
#5 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#7 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /Users/shafiqmustapa/Sites/UltimateCRM/app/Http/Middleware/IsClient.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\IsClient->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/shafiqmustapa/Sites/UltimateCRM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /Users/shafiqmustapa/Sites/UltimateCRM/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 /Users/shafiqmustapa/Sites/UltimateCRM/server.php(20): require_once('/Users/shafiqmu...')
```

**Comment by shivampaw** [comment]
You seem to be accessing a route that is for Clients only. The super admin account isn't a client.

Is that URL linked anywhere or are you accessing it manually?

I will add a fix for it so that you get told it's a client only URL.

**Comment by sicksand** [comment]
it is still the same if i'm login using client credential. is there a checking is_admin() on the controller?

**Comment by shivampaw** [comment]
I'm not able to replicate this. How did you create the client? Through the admin interface?

Does the client show in the admin panel when you visit /clients?

**Comment by sicksand** [comment]
I'm creating client  via route register and add showRegistrationForm and the create function.

No. the client does not show in admin panel

**Comment by shivampaw** [comment]
You need to create the client through the admin panel. There is no register form needed.

**Comment by sicksand** [comment]
in the admin, i can only create admin. not client.

**Comment by shivampaw** [comment]
URL is /clients

**Comment by sicksand** [comment]
i will re-clone this and close this.

**Comment by sicksand** [comment]
I have made clean install.

1. clone repo
2. composer install
3. php artisan key:generate
4. php artisan migrate
5. php artisan super_admin:create
6. php artisan serve

still i got error while clicking project/invoice. when i enter /clients it says 'you cannot access this page'

![screen shot 2017-09-25 at 3 12 40 pm](https://user-images.githubusercontent.com/305408/30796365-4aebfe90-a204-11e7-8c32-f11506208955.png)

**Comment by shivampaw** [comment]
Okay so can you follow these steps:

Logout and then login as the admin send a screenshot. 
Press the admins button and send a screenshot of the result. 
Press the client menu button and send a screenshot of that as well. 
Create a client /clients/create and enter some data and try and make one. 
Logout and login as the client (password is emailed to the client so you’ll need to enter a valid email) and send screenshot. 

Thanks.

**Comment by sicksand** [comment]
![screencapture-localhost-8000-admins-1506324231700](https://user-images.githubusercontent.com/305408/30796774-163386a8-a206-11e7-9fdc-0461441fa409.png)
![screencapture-localhost-8000-login-1506324192948](https://user-images.githubusercontent.com/305408/30796775-180783c6-a206-11e7-8343-3f6e46858c3d.png)
 I can only do 1 & 2 .because there is no client menu button and when i type in the url '/clients/create' will lead me to 'you cannot access this page'

**Comment by shivampaw** [comment]
That’s odd. Check your database, what is the user id for your user?

**Comment by sicksand** [comment]
user id is 1

**Comment by shivampaw** [comment]
Can you update the email and password to something generic and send a dump of your database?

**Comment by sicksand** [comment]
[wasaporder-26-09-2017-localhost.sql.gz](https://github.com/shivampaw/UltimateCRM/files/1331715/wasaporder-26-09-2017-localhost.sql.gz)
here are my db dump.

**Comment by shivampaw** [comment]
Thanks. I will have a look and get back to you within 12 hours.

**Comment by sicksand** [comment]
hi @shivampaw , 

it's been 7 months. Are you going to maintain this anymore?

**Comment by shivampaw** [comment]
Hi @sicksand

Did you manage to get this working? As for new features, I’ve done what I intended to do so unless requests come in I think this is now feature finished. For bugs I’ll be maintaining it and keeping it up to date with Laravel versions. I’m going to be updating this to Laravel 5.5 which is a LTS release and be updating it every time a LTS comes up.

**Comment by sicksand** [comment]
hi @shivampaw ,

I am still cannot create clients. I'm just able create more super admins.

**Comment by shivampaw** [comment]
Are you trying this on a remote server or local one? Any chance I could login and check what’s going on?

**Comment by sicksand** [comment]
local.

**Comment by shivampaw** [comment]
Ok. Is the error still the same and the DB dump still the same?

**Comment by sicksand** [comment]
yeah. I just delete the folder and do the install again. same as I stated
before. there is no client button. could you show me your screenshot of the
dashboard.

**Comment by shivampaw** [comment]
![image](https://user-images.githubusercontent.com/11842979/38194371-0d9969ba-366f-11e8-8b25-582c485fba34.png)

**Comment by shivampaw** [comment]
What branch are you using? Master? I'm gonna put some debugging code in on the develop branch. Gimme a few minutes.

**Comment by shivampaw** [comment]
Ok can you clone and look at the develop branch. Run the super_admin:create and then send me a screenshot of what the dashboard looks like when you log in.

Thanks

**Comment by shivampaw** [comment]
Looking at the codebase it seems like in your users table the is_admin column for your super admin account is false, this should be true. 

I've checked your DB dump but it shows true. I've modified the code for the isAdmin check to see if it helps. Take a look at the develop branch and see if it works now please.

**Comment by shivampaw** [comment]
(PHP 7.1.3) is required now by the way

I believe that now if you use the develop branch your issue should be fixed. Let me know if it is. If it is then I will get v5 out in the next couple of days.

Note that the develop branch does have some new features like:

Overdue invoice notifications
Project accepted notifications

and when i release it to the master branch it will be on Laravel 5.5 and Bootstrap 4.

**Comment by sicksand** [comment]
sorry for the late reply (i'm in gmt+8).

![screen shot 2018-04-03 at 10 33 33 am](https://user-images.githubusercontent.com/305408/38226136-9c7dfa86-372a-11e8-922a-03aa5ed5aaf2.png)

finally after checkout to develop branch, the client menu is appear. thanks.

**Comment by shivampaw** [comment]
Brilliant :)
